<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\instalacion\controllers;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template\html;
use html\dp_colonia_postal_html;
use html\ins_tipo_zona_html;
use html\ins_zona_html;
use models\ins_zona;
use PDO;
use stdClass;

class controlador_ins_zona extends system {

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(), stdClass $paths_conf = new stdClass()){
        $modelo = new ins_zona(link: $link);

        $html = new ins_zona_html(html: $html);
        $this->rows_lista[] = 'ins_tipo_zona_id';
        $this->rows_lista[] = 'dp_colonia_postal_id';
        $obj_link = new links_menu($this->registro_id);
        parent::__construct(html:$html, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Zona';

    }
    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar template', data: $r_alta, header: $header, ws: $ws);
        }

        $select = (new ins_tipo_zona_html(html: $this->html_base))->select_ins_tipo_zona_id(cols:12,con_registros: true,
            id_selected: -1, link: $this->link);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select, header: $header, ws: $ws);
        }

        $this->inputs->select = new stdClass();
        $this->inputs->select->ins_tipo_zona_id = $select;

        $select = (new dp_colonia_postal_html(html: $this->html_base))->select_dp_colonia_postal_id(cols:12,con_registros: true,
            id_selected: -1, link: $this->link);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select, header: $header, ws: $ws);
        }

        $this->inputs->select->dp_colonia_postal_id = $select;
        return $r_alta;

    }

    public function modifica(bool $header, bool $ws = false, string $breadcrumbs = '', bool $aplica_form = true,
                             bool $muestra_btn = true): array|string
    {
        $r_modifica =  parent::modifica($header, $ws, $breadcrumbs, $aplica_form, $muestra_btn); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_modifica, header: $header,ws:$ws);
        }

        $select = (new ins_tipo_zona_html(html: $this->html_base))->select_ins_tipo_zona_id(cols:12,con_registros:true,
            id_selected:$this->row_upd->ins_tipo_zona_id, link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select, header: $header, ws: $ws);
        }

        $this->inputs->select = new stdClass();
        $this->inputs->select->ins_tipo_zona_id = $select;
        $select = (new dp_colonia_postal_html(html: $this->html_base))->select_dp_colonia_postal_id(cols:12,con_registros:true,
            id_selected:$this->row_upd->dp_colonia_postal_id, link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select, header: $header, ws: $ws);
        }
        $this->inputs->select->dp_colonia_postal_id = $select;

        return $r_modifica;
    }
}
